### ISSUE TITLE
Seems like data isn't following the parents correctly

### ISSUE THREAD

**Issue by darkzeroman** [go-playground/locales#19]
es-mx's `group` shouldn't be `.`: [link](https://github.com/go-playground/locales/blob/master/es_MX/es_MX.go#L52
)
From CLDR's JSON data: [link](https://github.com/unicode-cldr/cldr-numbers-full/blob/fff6c812cf88feaf316fef83fbda092d02dadefa/main/es-MX/numbers.json#L20)

es's group is `'.'`.

I think the parentLocales aren't being followed correctly. But I will explore soon to learn more.

**Comment by joeybloggs** [comment]
I just haven’t found time to covert over to using the JSON data/repos; currently still using the XML data.

my workload is pretty heavy right now, don’t know when I’ll get a chance to look into it

**Comment by vvohra** [comment]
Made a PR: #20

**Comment by vvohra** [comment]
@joeybloggs this can be closed.
