### ISSUE TITLE
Go 1.10: ru_test.go:932: Errorf call has arguments but no formatting directives

### ISSUE THREAD

**Issue by nim-nim** [go-playground/locales#21]
Release 0.12.0 does not pass unit tests with Go 1.10. At least:

```
+ GOPATH=/builddir/build/BUILD/locales-0.12.0/_build:/usr/share/gocode
+ go test -buildmode pie -compiler gc -ldflags '-extldflags '\''-Wl,-z,relro  '\'''
# github.com/go-playground/locales/ru
./ru_test.go:932: Errorf call has arguments but no format
```

**Comment by joeybloggs** [comment]
Hey @nim-nim looks like it was a leftover error from the last PR, just release v0.12.1 so it should be fixed once you update :)

please let me know if it's working for you now as well :)

**Comment by nim-nim** [comment]
Sure, will retest now, thank you for caring!

**Comment by joeybloggs** [comment]
👍
