### ISSUE TITLE
How to update the CLDR version

### ISSUE THREAD

**Issue by cchung100m** [go-playground/locales#29]
Hi @deankarn 

It is been a while since you updated this repo to CLDR version `32.0.1`, currently, the latest stable version is 36.0.0 which released last Oct. If you are not available, I'd like to help the work if you could share the steps on updating the CLDR for `go-playground/locales`

many thanks,

**Comment by deankarn** [comment]
Hey @cchung100m here are the instructions https://github.com/go-playground/locales/tree/master/cmd

sorry for the lateness of my reply

**Comment by cchung100m** [comment]
@deankarn 

Thanks for the reply. I would update it once I am available. :)
