### ISSUE TITLE
golang.org/x/text v0.3.6 has a valnerability : GO-2022-1059

### ISSUE THREAD

**Issue by YoheiKonno** [go-playground/locales#42]
This library depends on golang.org/x/text v0.3.6 having a valnerability GO-2022-1059.  
ref. https://pkg.go.dev/vuln/GO-2022-1059

It should be updated v3.0.8 or higher.

**Comment by deankarn** [comment]
@YoheiKonno make a PR 🙏

**Comment by YoheiKonno** [comment]
Hi, I've PRed at https://github.com/go-playground/locales/pull/43. Check it please.

**Comment by deankarn** [comment]
Merged and in Release https://github.com/go-playground/locales/releases/tag/v0.14.1
